# Generated by Django 2.0.2 on 2018-02-21 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'start'), ('2', 'end')], help_text="Indicate if it's a call 'start' or 'end' record", max_length=1)),
                ('timestamp', models.PositiveIntegerField(help_text='The timestamp of when the event occured')),
                ('call_id', models.PositiveIntegerField(help_text='Unique for each call record pair')),
                ('source', models.CharField(help_text='The subscriber phone number that originated the call', max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: 'AAXXXXXXXXX'.Where AA is the area code and XXXXXXXXX is the phone number.", regex='^\\d{10,11}$')])),
                ('destination', models.CharField(help_text='The subscriber phone number that originated the call', max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: 'AAXXXXXXXXX'.Where AA is the area code and XXXXXXXXX is the phone number.", regex='^\\d{10,11}$')])),
            ],
            options={
                'ordering': ('call_id', 'timestamp', 'type'),
            },
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['call_id', 'type'], name='call_id_type_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['call_id', 'timestamp', 'type'], name='call_id_timestamp_type_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecord',
            index=models.Index(fields=['source', 'timestamp'], name='source_timestamp_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='callrecord',
            unique_together={('call_id', 'type')},
        ),
    ]
