# Generated by Django 2.0.2 on 2018-03-08 11:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import util.funcs


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180301_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='The subscriber phone number that originated the call', max_length=11, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message="Phone number must be entered in the format: 'AAXXXXXXXXX'. Where AA is the area code and XXXXXXXXX is the phone number.", regex='^\\d{10,11}$')])),
                ('period', models.CharField(default=util.funcs.get_last_month, help_text='The reference period (month/year) (optional)', max_length=7, validators=[django.core.validators.RegexValidator(message="Invalid period. Period must be entered in the format: 'YYYY-MM'. Where YYYY is the year and MM is the month.", regex='^\\d{4}-\\d{2}$')])),
            ],
            options={
                'ordering': ('source', 'period'),
            },
        ),
        migrations.CreateModel(
            name='BillLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(help_text='The phone number receiving the call', max_length=11, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message="Phone number must be entered in the format: 'AAXXXXXXXXX'. Where AA is the area code and XXXXXXXXX is the phone number.", regex='^\\d{10,11}$')])),
                ('start_date_time', models.DateTimeField(help_text='start date time: e.g. 2018-03-01 14:32')),
                ('duration', models.DurationField(help_text='call duration (hour, minute and seconds): e.g. 0h35m42s ')),
                ('price', models.DecimalField(decimal_places=2, help_text='call price: e.g. R$ 3,96 ', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('bill', models.ForeignKey(help_text='The bill informations', on_delete=django.db.models.deletion.CASCADE, related_name='bill_lines', to='app.Bill')),
            ],
            options={
                'ordering': ('bill', 'start_date_time'),
            },
        ),
        migrations.AlterField(
            model_name='callrecord',
            name='destination',
            field=models.CharField(help_text='The phone number receiving the call', max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message="Phone number must be entered in the format: 'AAXXXXXXXXX'. Where AA is the area code and XXXXXXXXX is the phone number.", regex='^\\d{10,11}$')]),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['source', 'period'], name='app_bill_source_bf989a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('source', 'period')},
        ),
        migrations.AddIndex(
            model_name='billline',
            index=models.Index(fields=['bill', 'start_date_time'], name='bill_startdatetime_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='billline',
            unique_together={('bill', 'start_date_time')},
        ),
    ]
