# Generated by Django 2.0.2 on 2018-03-16 20:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import util.funcs
import util.types_and_validators


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180308_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.SmallIntegerField(help_text='Start time of the standard call. e.g.: 06', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('end_time', models.SmallIntegerField(help_text='End time of the standard call. e.g.: 20', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('price_per_call_standard', models.DecimalField(decimal_places=2, help_text='Charge per call in standard period', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('price_per_call_reduced', models.DecimalField(decimal_places=2, help_text='Charge per call in reduced tariff period', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('price_per_minute_standard', models.DecimalField(decimal_places=2, help_text='Charge per minute in standard period', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('price_per_minute_reduced', models.DecimalField(decimal_places=2, help_text='Charge per minute in reduced tariff period', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='CallCharge',
        ),
        migrations.DeleteModel(
            name='StandingCharge',
        ),
        migrations.AlterField(
            model_name='bill',
            name='period',
            field=models.CharField(default=util.funcs.get_last_month, help_text='The reference period (month/year) (optional)', max_length=7, validators=[util.types_and_validators.PeriodYearMonth_validate]),
        ),
        migrations.AlterField(
            model_name='billline',
            name='bill',
            field=models.ForeignKey(help_text='The bill informations', on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='app.Bill'),
        ),
        migrations.AlterField(
            model_name='billline',
            name='duration',
            field=models.DurationField(help_text='call duration (hour, minute and seconds): e.g. 0:35:42 '),
        ),
        migrations.AlterField(
            model_name='billline',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='call price: e.g. 3.96 ', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
